//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceSerecu
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    public partial class Persona : object
    {
        
        private string CedulaIdentidadField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private string FechaNacimientoField;
        
        private string SexoField;
        
        private string EstadoCivilField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CedulaIdentidad
        {
            get
            {
                return this.CedulaIdentidadField;
            }
            set
            {
                this.CedulaIdentidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EstadoCivil
        {
            get
            {
                return this.EstadoCivilField;
            }
            set
            {
                this.EstadoCivilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoNacimiento", Namespace="http://tempuri.org/")]
    public partial class CertificadoNacimiento : object
    {
        
        private string CedulaIdentidadNacimientoField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private string FechaNacimientoField;
        
        private string NombrePadreField;
        
        private string ApellidosPadreField;
        
        private string NombreMadreField;
        
        private string ApellidosMadreField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CedulaIdentidadNacimiento
        {
            get
            {
                return this.CedulaIdentidadNacimientoField;
            }
            set
            {
                this.CedulaIdentidadNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombrePadre
        {
            get
            {
                return this.NombrePadreField;
            }
            set
            {
                this.NombrePadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ApellidosPadre
        {
            get
            {
                return this.ApellidosPadreField;
            }
            set
            {
                this.ApellidosPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NombreMadre
        {
            get
            {
                return this.NombreMadreField;
            }
            set
            {
                this.NombreMadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ApellidosMadre
        {
            get
            {
                return this.ApellidosMadreField;
            }
            set
            {
                this.ApellidosMadreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoMatrimonio", Namespace="http://tempuri.org/")]
    public partial class CertificadoMatrimonio : object
    {
        
        private string CedulaIndentidadMatrimonioField;
        
        private string CedulaIdentidadEsposoField;
        
        private string NombresEsposoField;
        
        private string PrimerApellidoEsposoField;
        
        private string SegundoApellidoEsposoField;
        
        private string CedulaIdentidadEsposaField;
        
        private string NombresEsposaField;
        
        private string PrimerApellidoEsposaField;
        
        private string SegundoApellidoEsposaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CedulaIndentidadMatrimonio
        {
            get
            {
                return this.CedulaIndentidadMatrimonioField;
            }
            set
            {
                this.CedulaIndentidadMatrimonioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CedulaIdentidadEsposo
        {
            get
            {
                return this.CedulaIdentidadEsposoField;
            }
            set
            {
                this.CedulaIdentidadEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombresEsposo
        {
            get
            {
                return this.NombresEsposoField;
            }
            set
            {
                this.NombresEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PrimerApellidoEsposo
        {
            get
            {
                return this.PrimerApellidoEsposoField;
            }
            set
            {
                this.PrimerApellidoEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SegundoApellidoEsposo
        {
            get
            {
                return this.SegundoApellidoEsposoField;
            }
            set
            {
                this.SegundoApellidoEsposoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CedulaIdentidadEsposa
        {
            get
            {
                return this.CedulaIdentidadEsposaField;
            }
            set
            {
                this.CedulaIdentidadEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NombresEsposa
        {
            get
            {
                return this.NombresEsposaField;
            }
            set
            {
                this.NombresEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PrimerApellidoEsposa
        {
            get
            {
                return this.PrimerApellidoEsposaField;
            }
            set
            {
                this.PrimerApellidoEsposaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SegundoApellidoEsposa
        {
            get
            {
                return this.SegundoApellidoEsposaField;
            }
            set
            {
                this.SegundoApellidoEsposaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificadoDefuncion", Namespace="http://tempuri.org/")]
    public partial class CertificadoDefuncion : object
    {
        
        private string CedulaIdentidadDefuncionField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private string FechaDefuncionField;
        
        private string CausaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CedulaIdentidadDefuncion
        {
            get
            {
                return this.CedulaIdentidadDefuncionField;
            }
            set
            {
                this.CedulaIdentidadDefuncionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FechaDefuncion
        {
            get
            {
                return this.FechaDefuncionField;
            }
            set
            {
                this.FechaDefuncionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Causa
        {
            get
            {
                return this.CausaField;
            }
            set
            {
                this.CausaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSerecu.WebServiceSerecuSoap")]
    public interface WebServiceSerecuSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _cedula del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerDatosResponse ObtenerDatos(ServiceReferenceSerecu.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ObtenerDatosAsync(ServiceReferenceSerecu.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _cedula del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _cedula del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _cedula del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse ObtenerCertificadoDefuncion(ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoDefuncion", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(ServiceReferenceSerecu.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _cedula;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string _cedula)
        {
            this._cedula = _cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(ServiceReferenceSerecu.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(ServiceReferenceSerecu.Persona ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest()
        {
        }
        
        public ObtenerCertificadoNacimientoRequest(ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _cedula;
        
        public ObtenerCertificadoNacimientoRequestBody()
        {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string _cedula)
        {
            this._cedula = _cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse()
        {
        }
        
        public ObtenerCertificadoNacimientoResponse(ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.CertificadoNacimiento ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody()
        {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(ServiceReferenceSerecu.CertificadoNacimiento ObtenerCertificadoNacimientoResult)
        {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest()
        {
        }
        
        public ObtenerCertificadoMatrimonioRequest(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _cedula;
        
        public ObtenerCertificadoMatrimonioRequestBody()
        {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string _cedula)
        {
            this._cedula = _cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse()
        {
        }
        
        public ObtenerCertificadoMatrimonioResponse(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.CertificadoMatrimonio ObtenerCertificadoMatrimonioResult;
        
        public ObtenerCertificadoMatrimonioResponseBody()
        {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(ServiceReferenceSerecu.CertificadoMatrimonio ObtenerCertificadoMatrimonioResult)
        {
            this.ObtenerCertificadoMatrimonioResult = ObtenerCertificadoMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequestBody Body;
        
        public ObtenerCertificadoDefuncionRequest()
        {
        }
        
        public ObtenerCertificadoDefuncionRequest(ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _cedula;
        
        public ObtenerCertificadoDefuncionRequestBody()
        {
        }
        
        public ObtenerCertificadoDefuncionRequestBody(string _cedula)
        {
            this._cedula = _cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoDefuncionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoDefuncionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponseBody Body;
        
        public ObtenerCertificadoDefuncionResponse()
        {
        }
        
        public ObtenerCertificadoDefuncionResponse(ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoDefuncionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDefuncionResult;
        
        public ObtenerCertificadoDefuncionResponseBody()
        {
        }
        
        public ObtenerCertificadoDefuncionResponseBody(ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDefuncionResult)
        {
            this.ObtenerCertificadoDefuncionResult = ObtenerCertificadoDefuncionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebServiceSerecuSoapChannel : ServiceReferenceSerecu.WebServiceSerecuSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebServiceSerecuSoapClient : System.ServiceModel.ClientBase<ServiceReferenceSerecu.WebServiceSerecuSoap>, ServiceReferenceSerecu.WebServiceSerecuSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSerecuSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSerecuSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSerecuSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSerecuSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSerecuSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSerecuSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSerecuSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSerecuSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerDatosResponse ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerDatos(ServiceReferenceSerecu.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatos(request);
        }
        
        public ServiceReferenceSerecu.Persona ObtenerDatos(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerDatosRequest inValue = new ServiceReferenceSerecu.ObtenerDatosRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerDatosRequestBody();
            inValue.Body._cedula = _cedula;
            ServiceReferenceSerecu.ObtenerDatosResponse retVal = ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerDatosAsync(ServiceReferenceSerecu.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerDatosResponse> ObtenerDatosAsync(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerDatosRequest inValue = new ServiceReferenceSerecu.ObtenerDatosRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerDatosRequestBody();
            inValue.Body._cedula = _cedula;
            return ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoNacimiento(ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public ServiceReferenceSerecu.CertificadoNacimiento ObtenerCertificadoNacimiento(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body._cedula = _cedula;
            ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse retVal = ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse> ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoNacimientoAsync(ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest request)
        {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body._cedula = _cedula;
            return ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoMatrimonio(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public ServiceReferenceSerecu.CertificadoMatrimonio ObtenerCertificadoMatrimonio(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body._cedula = _cedula;
            ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse retVal = ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse> ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoMatrimonioAsync(ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest request)
        {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body._cedula = _cedula;
            return ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoDefuncion(ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDefuncion(request);
        }
        
        public ServiceReferenceSerecu.CertificadoDefuncion ObtenerCertificadoDefuncion(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body._cedula = _cedula;
            ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse retVal = ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoDefuncion(inValue);
            return retVal.Body.ObtenerCertificadoDefuncionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse> ServiceReferenceSerecu.WebServiceSerecuSoap.ObtenerCertificadoDefuncionAsync(ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest request)
        {
            return base.Channel.ObtenerCertificadoDefuncionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSerecu.ObtenerCertificadoDefuncionResponse> ObtenerCertificadoDefuncionAsync(string _cedula)
        {
            ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest inValue = new ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequest();
            inValue.Body = new ServiceReferenceSerecu.ObtenerCertificadoDefuncionRequestBody();
            inValue.Body._cedula = _cedula;
            return ((ServiceReferenceSerecu.WebServiceSerecuSoap)(this)).ObtenerCertificadoDefuncionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSerecuSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSerecuSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSerecuSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56668/WebServiceSerecu.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSerecuSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56668/WebServiceSerecu.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSerecuSoap,
            
            WebServiceSerecuSoap12,
        }
    }
}
