//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datos", Namespace="http://tempuri.org/")]
    public partial class Datos : object
    {
        
        private string ciField;
        
        private string NombresField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ci
        {
            get
            {
                return this.ciField;
            }
            set
            {
                this.ciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerDatosResponse> ObtenerDatosAsync(ServiceReference1.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.VerificarDatosResponse> VerificarDatosAsync(ServiceReference1.VerificarDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest()
        {
        }
        
        public ObtenerDatosRequest(ServiceReference1.ObtenerDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _ci;
        
        public ObtenerDatosRequestBody()
        {
        }
        
        public ObtenerDatosRequestBody(string _ci)
        {
            this._ci = _ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse()
        {
        }
        
        public ObtenerDatosResponse(ServiceReference1.ObtenerDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Datos ObtenerDatosResult;
        
        public ObtenerDatosResponseBody()
        {
        }
        
        public ObtenerDatosResponseBody(ServiceReference1.Datos ObtenerDatosResult)
        {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.VerificarDatosRequestBody Body;
        
        public VerificarDatosRequest()
        {
        }
        
        public VerificarDatosRequest(ServiceReference1.VerificarDatosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _PrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _SegundoApellido;
        
        public VerificarDatosRequestBody()
        {
        }
        
        public VerificarDatosRequestBody(string _ci, string _Nombres, string _PrimerApellido, string _SegundoApellido)
        {
            this._ci = _ci;
            this._Nombres = _Nombres;
            this._PrimerApellido = _PrimerApellido;
            this._SegundoApellido = _SegundoApellido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.VerificarDatosResponseBody Body;
        
        public VerificarDatosResponse()
        {
        }
        
        public VerificarDatosResponse(ServiceReference1.VerificarDatosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarDatosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarDatosResult;
        
        public VerificarDatosResponseBody()
        {
        }
        
        public VerificarDatosResponseBody(bool VerificarDatosResult)
        {
            this.VerificarDatosResult = VerificarDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WebServiceSoapChannel : ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebServiceSoap>, ServiceReference1.WebServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ObtenerDatosResponse> ServiceReference1.WebServiceSoap.ObtenerDatosAsync(ServiceReference1.ObtenerDatosRequest request)
        {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ObtenerDatosResponse> ObtenerDatosAsync(string _ci)
        {
            ServiceReference1.ObtenerDatosRequest inValue = new ServiceReference1.ObtenerDatosRequest();
            inValue.Body = new ServiceReference1.ObtenerDatosRequestBody();
            inValue.Body._ci = _ci;
            return ((ServiceReference1.WebServiceSoap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.VerificarDatosResponse> ServiceReference1.WebServiceSoap.VerificarDatosAsync(ServiceReference1.VerificarDatosRequest request)
        {
            return base.Channel.VerificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.VerificarDatosResponse> VerificarDatosAsync(string _ci, string _Nombres, string _PrimerApellido, string _SegundoApellido)
        {
            ServiceReference1.VerificarDatosRequest inValue = new ServiceReference1.VerificarDatosRequest();
            inValue.Body = new ServiceReference1.VerificarDatosRequestBody();
            inValue.Body._ci = _ci;
            inValue.Body._Nombres = _Nombres;
            inValue.Body._PrimerApellido = _PrimerApellido;
            inValue.Body._SegundoApellido = _SegundoApellido;
            return ((ServiceReference1.WebServiceSoap)(this)).VerificarDatosAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54592/WebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceSoap,
           
        }
    }
}
